trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - .vscode/*
    - .git*
    - .editorconfig
    - .nuke
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
      - master

phases:
  - phase: Build
    variables:
      CI: 'true'
      Configuration: Release
      Verbosity: Normal
      Coverage: '$(Agent.BuildDirectory)/c'
      Artifacts: $(Build.ArtifactStagingDirectory)
      system.enableAccessToken: 'true'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
      NuGetVersion: "5.3.0"
      NodeVersion: "10.x"
      ConnectedServiceName: 'RocketSurgeonsGuild Marketplace'
      VstsAccountId: 'rocketsurgeonsguild'
    steps:
    - task: NuGetToolInstaller@1
      displayName: Install nuget $(NuGetVersion)
      inputs:
        versionSpec: $(NuGetVersion)

    - task: NodeTool@0
      displayName: Install node $(NodeVersion)
      inputs:
        versionSpec: $(NodeVersion)

    - task: cake-build.cake.cake-build-task.Cake@0
      inputs:
        message: build
        script: "cakefile.cake"
        verbosity: $(Verbosity)
        arguments: '-Configuration="$(Configuration)" -Artifacts="$(Artifacts)" -Coverage="$(Coverage)"'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
      displayName: Publish Extension
      inputs:
        extensionVersion: '$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.CommitsSinceVersionSource)'
        connectedServiceName: '$(ConnectedServiceName)'
        shareWith: '$(VstsAccountId)'
        updateTasksVersion: true
        extensionVisibility: private
        extensionPricing: free
      condition: and(succeeded(), variables['GitVersion.CommitsSinceVersionSource'])

    - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
      displayName: Publish Extension
      inputs:
        extensionVersion: '$(GitVersion.MajorMinorPatch)'
        connectedServiceName: '$(ConnectedServiceName)'
        shareWith: '$(VstsAccountId)'
        updateTasksVersion: true
        extensionVisibility: private
        extensionPricing: free
      condition: and(succeeded(), not(variables['GitVersion.CommitsSinceVersionSource']))

